name: cGenerators
version: 2.0.0
main: com.skyblock.cgenerators.CGenerators
api-version: 1.13
author: SkyblockServer
description: Professional cobblestone generator upgrade system with multi-language support
website: https://yourserver.com

depend: [Vault]

commands:
  cgenerators:
    description: Open generator upgrade menu
    aliases: [cgen, generators, gen]
    permission: cgenerators.use
  cgeneratorsadmin:
    description: Admin commands
    aliases: [cgenadmin, genadmin]
    permission: cgenerators.admin

permissions:
  cgenerators.use:
    description: Use generator menu
    default: true
  cgenerators.admin:
    description: Admin commands
    default: op
  cgenerators.tier.1:
    description: Tier 1 generator
    default: true
  cgenerators.tier.2:
    description: Tier 2 generator
    default: false
  cgenerators.tier.3:
    description: Tier 3 generator
    default: false
  cgenerators.tier.4:
    description: Tier 4 generator
    default: false
  cgenerators.tier.5:
    description: Tier 5 generator
    default: false
